#!/usr/bin/env python3
"""
Debug script to understand what prompt is being generated by the job interview scenario.
This will help us identify why the AI thinks it's the candidate instead of the interviewer.
"""

import sys
import os

# Add the project root to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from services.llm.scenarios.job_interview import get_interview_prompt

def debug_prompt_generation():
    """Debug the prompt generation to identify the personality confusion issue."""
    
    print("=" * 80)
    print("DEBUG: JOB INTERVIEW PROMPT GENERATION")
    print("=" * 80)
    
    # Test with default parameters (what Ollama client currently uses)
    print("\n1. DEFAULT PARAMETERS (current Ollama client behavior):")
    print("-" * 50)
    
    default_prompt = get_interview_prompt()
    print("Generated prompt:")
    print(default_prompt)
    
    print("\n" + "=" * 80)
    
    # Test with some context to see how it changes
    print("\n2. WITH SAMPLE CONTEXT:")
    print("-" * 50)
    
    sample_context = "Candidate introduced themselves as John Doe, a software engineer with 3 years experience."
    
    context_prompt = get_interview_prompt(
        position_type="software_engineer",
        interview_style="neutral", 
        experience_level="mid_level",
        company_type="tech_startup",
        stage="technical_assessment",
        context_memory=sample_context
    )
    
    print("Generated prompt with context:")
    print(context_prompt)
    
    print("\n" + "=" * 80)
    
    # Test different stages
    print("\n3. DIFFERENT INTERVIEW STAGES:")
    print("-" * 50)
    
    stages = ["introduction", "background_experience", "technical_assessment", "behavioral_assessment"]
    
    for stage in stages:
        print(f"\n--- STAGE: {stage} ---")
        stage_prompt = get_interview_prompt(
            position_type="software_engineer",
            stage=stage,
            context_memory="Brief conversation context"
        )
        
        # Show just the key parts
        lines = stage_prompt.split('\n')
        for i, line in enumerate(lines[:15]):  # First 15 lines
            print(f"{i+1:2d}: {line}")
        print("    ... (truncated)")
        
    print("\n" + "=" * 80)
    print("DEBUG COMPLETE")
    print("=" * 80)

if __name__ == "__main__":
    debug_prompt_generation()
