#!/usr/bin/env python3
"""
Test script to debug the exact prompt being generated by the Ollama client.
This will help us understand why the AI is confused about its role.
"""

import sys
import os
import random

# Add the project root to Python path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

def test_prompt_generation():
    """Test the actual prompt generation process that the Ollama client uses."""
    
    print("=" * 80)
    print("DEBUGGING AI PERSONALITY CONFUSION")
    print("=" * 80)
    
    # Import the scenario function
    from services.llm.scenarios.job_interview import get_interview_prompt
    
    print("\n1. TESTING DEFAULT PROMPT (what Ollama client currently uses)")
    print("-" * 60)
    
    # This is exactly what the Ollama client calls
    default_prompt = get_interview_prompt()
    
    print("Generated system prompt:")
    print(default_prompt)
    
    print("\n" + "=" * 80)
    
    # Test how the Ollama client formats this into a full prompt
    print("\n2. TESTING FULL FORMATTED PROMPT")
    print("-" * 60)
    
    # Simulate what _format_prompt does
    system_prompt = default_prompt
    
    # Add brevity instruction (from Ollama client)
    formatted_prompt = system_prompt + "\n\n"
    formatted_prompt += "IMPORTANT: Keep your responses very brief - no more than 2-3 sentences. " \
                       "Provide direct and concise answers without unnecessary elaboration.\n\n"
    
    # Add stage guidance (introduction stage)
    formatted_prompt += "This is the beginning of the conversation. Introduce yourself warmly.\n\n"
    
    # Add a sample user input (first interaction)
    user_input = "Hi, I'm John Smith, thanks for taking the time to meet with me today."
    formatted_prompt += f"Candidate: {user_input}\n\nInterviewer:"
    
    print("FULL FORMATTED PROMPT:")
    print(formatted_prompt)
    
    print("\n" + "=" * 80)
    
    # Test with some context to see if that changes behavior
    print("\n3. TESTING WITH CONTEXT")
    print("-" * 60)
    
    context_memory = "The candidate introduced themselves as John Smith, a software engineer with 3 years experience at TechCorp."
    
    context_prompt = get_interview_prompt(
        position_type="software_engineer",
        interview_style="neutral",
        experience_level="mid_level", 
        company_type="tech_startup",
        stage="background_experience",
        context_memory=context_memory
    )
    
    print("System prompt with context:")
    print(context_prompt)
    
    print("\n" + "=" * 80)
    
    # Test the specific problematic scenario from the logs
    print("\n4. SIMULATING PROBLEMATIC SCENARIO")
    print("-" * 60)
    
    # Simulate second response where AI gets confused
    system_prompt_2 = get_interview_prompt(
        context_memory="Previous conversation context about the candidate's background"
    )
    
    formatted_prompt_2 = system_prompt_2 + "\n\n"
    formatted_prompt_2 += "IMPORTANT: Keep your responses very brief - no more than 2-3 sentences.\n\n"
    
    # Previous exchange
    formatted_prompt_2 += "Candidate: Hi, I'm John Smith, thanks for taking the time to meet with me today.\n"
    formatted_prompt_2 += "Interviewer: So, Taylor Wilson, right? Senior Software Engineer at A Tech...\n"
    
    # Current user input
    formatted_prompt_2 += "Candidate: Yes, that's right. I've been working there for about 3 years now.\n\nInterviewer:"
    
    print("FORMATTED PROMPT FOR SECOND RESPONSE:")
    print(formatted_prompt_2)
    
    print("\n" + "=" * 80)
    print("ANALYSIS COMPLETE")
    print("=" * 80)

if __name__ == "__main__":
    test_prompt_generation()
